server:
  port: 9001
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: alibaba-provider
#    数据库配置
  datasource:
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?characterEncoding=utf8&serverTimezone=UTC
    username: root
logging:
  level:
#    处理日志频繁打印c.a.n.client.config.impl.ClientWorker    : get changedGroupKeys:[]
    com.alibaba.nacos.client.config.impl: WARN
dubbo:
  protocol:
    name: dubbo
#    -1 表示自增端口，从 20880 开始
    port: -1
  #Dubbo服务注册中心的配置地址，它的值spring-cloud://localhost表示挂载到Spring Cloud注册中心，不配置的话会提示没有配置注册中心的错误。
  registry:
    address: spring-cloud://127.0.0.1
  scan:
    #Dubbo服务实现类的扫描基准包路径 也可以通过标注@DubboComponentScan来实现基准包扫描。
    base-packages: com.xue.demo.alibaba.provider.dubboSpi
